# Build
[build]
  command = "npm run build"
  publish = "dist"

# SPA routing: send all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets (adjust paths if you fingerprint assets)
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
